
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class frameMain extends javax.swing.JFrame {

    String nol_jam,nol_menit,nol_detik;
    /**
     * Creates new form frameMain
     */
    public frameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Jam = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tfKelas = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfNis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbPerempuan = new javax.swing.JRadioButton();
        tfNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAlamat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tfTL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 410, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic Schools");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 170, 20);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        Jam.setText("jam");
        jPanel1.add(Jam);
        Jam.setBounds(640, 40, 140, 30);

        tanggal.setText("tgl");
        jPanel1.add(tanggal);
        tanggal.setBounds(640, 10, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 90);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("NIS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 130, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 130, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Nama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 130, 20);

        buttonGroup1.add(rbLaki);
        rbLaki.setText("Laki-Laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });
        getContentPane().add(rbLaki);
        rbLaki.setBounds(20, 250, 80, 23);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 280, 130, 20);
        getContentPane().add(tfKelas);
        tfKelas.setBounds(20, 300, 150, 30);
        getContentPane().add(tfEmail);
        tfEmail.setBounds(20, 350, 150, 30);
        getContentPane().add(tfNis);
        tfNis.setBounds(20, 150, 150, 30);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 330, 130, 20);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("DataSiswa");
        jPanel2.add(label4);
        label4.setBounds(70, 0, 70, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 220, 20);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");
        jPanel3.add(rbPerempuan);
        rbPerempuan.setBounds(100, 130, 90, 23);

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        jPanel3.add(tfNama);
        tfNama.setBounds(10, 80, 150, 30);

        tfAlamat.setColumns(20);
        tfAlamat.setRows(5);
        jScrollPane1.setViewportView(tfAlamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 400, 200, 80);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Alamat");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 380, 130, 20);
        jPanel3.add(tfTL);
        tfTL.setBounds(10, 280, 150, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Tempat Lahir");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 260, 130, 20);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("Tanggal Lahir");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 320, 130, 20);
        jPanel3.add(jDateChooser1);
        jDateChooser1.setBounds(10, 340, 150, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 120, 220, 490);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(null);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(20, 10, 60, 30);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(100, 10, 80, 30);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(197, 10, 70, 30);

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(280, 10, 80, 30);

        jButton5.setText("Edit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(380, 10, 60, 30);

        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(460, 10, 80, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(240, 100, 590, 50);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(null);

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "JenisKelamin", "Kelas", "Email", "TempatLahir", "Tanggal Lahir", "Alamat"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableData);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 570, 310);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(240, 160, 590, 450);

        setBounds(0, 0, 861, 655);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed

    }//GEN-LAST:event_tfNamaActionPerformed

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        int baris = tableData.getSelectedRow();
        if (baris != -1) {
            tfNis.setText(tableData.getValueAt(baris, 0).toString());
            tfNama.setText(tableData.getValueAt(baris, 1).toString());
            if ("Laki-Laki".equals(tableData.getValueAt(baris, 2).toString())) {
                rbLaki.setSelected(true);
            } else {
                rbPerempuan.setSelected(true);
            }
            tfKelas.setText(tableData.getValueAt(baris, 3).toString());
            tfEmail.setText(tableData.getValueAt(baris, 4).toString());
            tfAlamat.setText(tableData.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_tableDataMouseClicked

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ("".equals(tfNis.getText()) || "".equals(tfAlamat.getText()) || 
                "".equals(tfNama.getText()) || "".equals(tfEmail.getText()) ||
                "".equals(tfKelas.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi data", "Error",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (rbLaki.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            
//            String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat) " +
//                    "VALUES('"+tfNis.getText()+"','"+tfNama.getText()+"','"+JK+"','"
//                    +tfKelas.getText()+"','"+tfEmail.getText()+"','"+tfAlamat.getText()+"')";
            String SQL = "INSERT INTO t_siswa VALUES "
                    +"('"+tfNis.getText()+"', '"
                    +tfNama.getText()+"', '"+tanggal+"', '"+JK+"', '"
                    +"', '"+tfTL.getText()+"', '"
                    +tfAlamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil DItambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal ditambahkan","Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int baris = tableData.getSelectedRow();
        if (baris!= -1) {
            String NIS = tableData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa Where NIS ='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }       
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tfAlamat.setText("");
        tfEmail.setText("");
        tfKelas.setText("");
        tfNama.setText("");
        tfNis.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        selectData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if ("".equals(tfNis.getText()) || "".equals(tfAlamat.getText()) || 
                "".equals(tfNama.getText()) || "".equals(tfEmail.getText()) ||
                "".equals(tfKelas.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi data", "Error",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (rbLaki.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            
//            String SQL = "UPDATE t_siswa SET "
//                    + "WHERE NamaSiswa='"+tfNama.getText()
//                    +"',"+ "WHERE JenisKelamin='"+JK+"',"
//                    + "WHERE Kelas='"+tfKelas.getText()+"',"
//                    + "WHERE Email='"+tfEmail.getText()+"',"
//                    + "WHERE Alamat='"+tfAlamat.getText()+"'"
//                    + "WHERE NIS='"+tfNis.getText()+"'";
            String SQL = "UPDATE t_siswa SET "
                    + "WHERE NamaSiswa='"+tfNama.getText()
                    + "TanggalLahir'"+tanggal
                    + "',"+ "JenisKelamin='"+JK
                    + "',"+ "Kelas='"+tfKelas.getText()
                    + "',"+ "Email='"+tfEmail.getText()
                    + "',"+ "TempatLahir='"+tfTL.getText()
                    + "'," +"Alamat='"+tfAlamat.getText()+"'"
                    + "' WHERE NIS='"+tfNis.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else  {
                JOptionPane.showMessageDialog(this, "Update data gagal", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        try {
             tableData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    public void setTanggal() {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        tanggal.setText(kal.format(skrg));
    }
    
    public void setJam() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                Date dt = new Date();
//                String nol_jam = null,nol_menit = null,nol_detik = null;
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                Jam.setText("Jam "+jam+" : "+menit+" : "+detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
    
    private void selectData() {
        String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while (rs.next()) {                
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String JenisKelamin = "";
                if ("L".equals(rs.getString(3))) {
                    JenisKelamin = "Laki-Laki";
                } else {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(4);
                String Email = rs.getString(5);
                String Alamat = rs.getString(6);
                String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frameMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableData.setModel(dtm);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jam;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label4;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tableData;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTextArea tfAlamat;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfKelas;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNis;
    private javax.swing.JTextField tfTL;
    // End of variables declaration//GEN-END:variables

    
}
